FROM httpd:2.4.41-alpine 

ARG WEB_USER
ARG WEB_GROUP
ARG APACHE_EXPOSED_PORT
ARG APACHE_ROOT_DIR
ARG PHP_APP_DIR
ARG SERVER_NAME
ARG PHP_CONTAINER_NAME

COPY httpd.conf /usr/local/apache2/conf/httpd.conf

RUN apk update && apk upgrade 

RUN apk add \
mysql-client nmap wget nano openssl libzip-dev zip unzip shadow 

RUN \
usermod -u 1000 ${WEB_USER} && \
groupmod -g 1000 ${WEB_GROUP} && \
chgrp -R ${WEB_GROUP} ${APACHE_ROOT_DIR}

RUN chgrp -R ${WEB_GROUP} ${APACHE_ROOT_DIR}/conf/httpd.conf && \
    chgrp -R ${WEB_GROUP} ${APACHE_ROOT_DIR}/conf/extra/httpd-vhosts.conf
