FROM php:7.4.7-fpm-alpine

ARG WEB_GROUP
ARG PHP_ROOT_DIR
ARG PHP_USERNAME
ARG PHP_USER_PASSWORD

COPY www.conf ${PHP_ROOT_DIR}/php-fpm.d/www.conf

RUN apk update && apk upgrade
RUN docker-php-ext-install pdo pdo_mysql mysqli

RUN apk add nmap wget nano
RUN apk add openssl libzip-dev zip unzip mysql-client shadow bash git
RUN usermod -u 1000 ${PHP_USERNAME}
RUN groupmod -g 1000 ${PHP_USERNAME}

USER ${PHP_USERNAME}
RUN \
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
php composer-setup.php && \
php -r "unlink('composer-setup.php');"

USER root
RUN mv composer.phar /usr/local/bin/composer

USER ${PHP_USERNAME}