FROM php:7.1.31-fpm-alpine

ARG WEB_GROUP
ARG PHP_ROOT_DIR
ARG PHP_USERNAME
ARG PHP_USER_PASSWORD

COPY www.conf ${PHP_ROOT_DIR}/php-fpm.d/www.conf

# RUN apt update && \
# apt -y upgrade && docker-php-ext-install pdo pdo_mysql mbstring

RUN apk update && apk upgrade
RUN docker-php-ext-install pdo pdo_mysql mbstring mysqli 
# RUN bash bash-completion

# RUN apt -y update 
# RUN apt install -y net-tools iputils-ping nmap wget nano network-manager
# RUN apt install -y apt-utils openssl libzip-dev zip unzip mysql-client
RUN apk add nmap wget nano
RUN apk add openssl libzip-dev zip unzip mysql-client shadow bash
RUN usermod -u 1000 ${PHP_USERNAME}
# RUN apk openssh openrc
# RUN rc-update add sshd
# RUN useradd -G ${WEB_GROUP} -p ${PHP_USER_PASSWORD} --create-home --shell /bin/bash ${PHP_USERNAME}
# RUN addgroup ${PHP_USERNAME} ${WEB_GROUP}

# RUN chgrp -R staff /usr/local/etc/php-fpm.d/www.conf

USER ${PHP_USERNAME}
RUN \
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
php composer-setup.php && \
php -r "unlink('composer-setup.php');"

USER root
RUN mv composer.phar /usr/local/bin/composer